# Generated by Django 5.2.17 on 2026-09-03 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên lớp học')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã tham gia lớp')),
                ('grade', models.CharField(choices=[('10', 'Khối 10'), ('11', 'Khối 11'), ('12', 'Khối 12'), ('HSG', 'Đội tuyển HSG'), ('OTHER', 'Khác')], default='12', max_length=20, verbose_name='Khối lớp')),
                ('school_year', models.CharField(blank=True, default='2025-2026', max_length=50, verbose_name='Năm học')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả / Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Danh sách học sinh')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_classes', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên phụ trách')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Danh sách lớp học',
                'ordering': ['-created_at'],
            },
        ),
    ]
