# Generated by Django 5.2.17 on 2026-09-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Bật bảo mật 2 lớp (2FA)'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Mã khôi phục 2FA'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mã bí mật 2FA'),
        ),
    ]
