# Generated by Django 5.2.17 on 2026-08-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_branch', models.CharField(choices=[('NONE', 'Chưa chọn'), ('CS', 'Khoa học Máy tính (CS)'), ('ICT', 'Tin học Ứng dụng (ICT)')], default='NONE', max_length=10, verbose_name='Nhánh Phần II đã chọn (Hard-lock)')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Đang làm bài'), ('SUBMITTED', 'Đã nộp bài'), ('LOCKED_VIOLATION', 'Bị khóa do gian lận (Quá số lần chuyển tab)'), ('CANCELLED', 'Đã hủy')], default='IN_PROGRESS', max_length=20, verbose_name='Trạng thái phiên thi')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bắt đầu')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian nộp bài')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tổng điểm')),
                ('part1_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Điểm Phần I')),
                ('part2_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Điểm Phần II')),
                ('part1_correct_count', models.IntegerField(default=0, verbose_name='Số câu đúng Phần I')),
                ('part2_correct_subitems_count', models.IntegerField(default=0, verbose_name='Tổng số ý đúng Phần II')),
                ('violation_count', models.IntegerField(default=0, verbose_name='Số lần cảnh báo vi phạm')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Đã bị khóa')),
                ('lock_reason', models.CharField(blank=True, max_length=255, verbose_name='Lý do khóa bài')),
                ('competency_scores', models.JSONField(blank=True, default=dict, verbose_name='Phân tích Năng lực (% Điểm theo danh mục)')),
            ],
            options={
                'verbose_name': 'Phiên làm bài thi',
                'verbose_name_plural': 'Danh sách Phiên thi',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part2_answers', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(default=False, verbose_name='Đúng hoàn toàn (Part I)')),
                ('correct_subitems_count', models.IntegerField(default=0, verbose_name='Số ý đúng (Part II)')),
                ('score_awarded', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Điểm đạt được')),
            ],
            options={
                'verbose_name': 'Câu trả lời của thí sinh',
                'verbose_name_plural': 'Chi tiết Câu trả lời',
            },
        ),
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('TAB_SWITCH', 'Chuyển Tab / Cửa sổ khác'), ('FULLSCREEN_EXIT', 'Thoát chế độ Toàn màn hình'), ('WINDOW_BLUR', 'Mất tiêu điểm chuột (Window Blur)'), ('DEVTOOLS_KEY', 'Cố gắng nhấn phím mở DevTools (F12/Ctrl+Shift+I)'), ('COPY_PASTE', 'Cố gắng Sao chép / Dán dữ liệu')], default='TAB_SWITCH', max_length=30)),
                ('violation_number', models.IntegerField(default=1, verbose_name='Lần vi phạm thứ')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, verbose_name='Thông tin chi tiết (URL, user-agent...)')),
            ],
            options={
                'verbose_name': 'Nhật ký Vi phạm',
                'verbose_name_plural': 'Nhật ký Vi phạm thi cử',
                'ordering': ['-timestamp'],
            },
        ),
    ]
