# Generated by Django 5.2.17 on 2026-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='question_order_index',
            field=models.IntegerField(default=1, verbose_name='Thứ tự câu hỏi'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_option_label',
            field=models.CharField(blank=True, max_length=10, verbose_name='Chữ cái đáp án chọn (A, B, C, D)'),
        ),
    ]
