# Generated by Django 5.2.17 on 2026-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_studentanswer_question_order_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='draft_answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu câu trả lời lưu nháp định kỳ'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='extra_time_minutes',
            field=models.IntegerField(default=0, verbose_name='Thời gian gia hạn thêm (phút)'),
        ),
    ]
