# Generated by Django 5.2.17 on 2026-09-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_examsession_draft_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='selected_branch',
            field=models.CharField(choices=[('NONE', 'Chưa chọn'), ('CS', 'Khoa học Máy tính (CS)'), ('ICT', 'Tin học Ứng dụng (ICT)'), ('BOTH', 'Cả CS và ICT')], default='NONE', max_length=10, verbose_name='Nhánh Phần II đã chọn (Hard-lock)'),
        ),
    ]
