# Generated by Django 5.2.17 on 2026-09-16 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_alter_examsession_selected_branch'),
        ('exams', '0015_exam_exams_exam_is_acti_ac5c7b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['student', 'exam', 'status'], name='assessment__student_c47106_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['exam', 'status'], name='assessment__exam_id_eb063a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['session', 'question'], name='assessment__session_bc6a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='violationlog',
            index=models.Index(fields=['session', 'timestamp'], name='assessment__session_2e2add_idx'),
        ),
    ]
