# Generated by Django 5.2.17 on 2026-09-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_examsession_assessment__student_c47106_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Nội dung thông báo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='assessment.examsession', verbose_name='Phiên thi')),
            ],
            options={
                'verbose_name': 'Thông báo phiên thi',
                'verbose_name_plural': 'Thông báo phiên thi',
                'ordering': ['-created_at'],
            },
        ),
    ]
