# Generated by Django 5.2.17 on 2026-09-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_exambroadcast'),
        ('exams', '0015_exam_exams_exam_is_acti_ac5c7b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exambroadcast',
            name='sitting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='exams.examsitting', verbose_name='Ca thi'),
        ),
    ]
