# Generated by Django 5.2.17 on 2026-09-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_alter_exambroadcast_sitting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['question_order_index'], 'verbose_name': 'Câu trả lời của thí sinh', 'verbose_name_plural': 'Chi tiết Câu trả lời'},
        ),
    ]
