# Generated by Django 5.2.17 on 2026-08-26 10:12

import django.db.models.deletion
import exams.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên đề thi')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả / Hướng dẫn')),
                ('duration_minutes', models.IntegerField(default=50, verbose_name='Thời gian làm bài (Phút)')),
                ('access_type', models.CharField(choices=[('PUBLIC', 'Tất cả học sinh (Công khai)'), ('PROTECTED', 'Cần mã Access Code'), ('ASSIGNED', 'Chỉ định theo Lớp / Đội tuyển')], default='PUBLIC', max_length=20, verbose_name='Chế độ truy cập')),
                ('access_code', models.CharField(blank=True, max_length=50, verbose_name='Mã truy cập / Mật khẩu đề')),
                ('allowed_classes', models.TextField(blank=True, help_text='Danh sách lớp được phép thi, phân cách bởi dấu phẩy (vd: 12A1, 12A2, Đội tuyển HSG)', verbose_name='Lớp được phân quyền')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('max_tab_violations', models.IntegerField(default=3, verbose_name='Số lần chuyển tab tối đa cho phép')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Đảo thứ tự câu hỏi')),
                ('shuffle_options', models.BooleanField(default=True, verbose_name='Đảo thứ tự phương án A/B/C/D')),
                ('part1_point_per_question', models.DecimalField(decimal_places=2, default=0.4, max_digits=4, verbose_name='Điểm mỗi câu Phần I (Trắc nghiệm)')),
                ('part2_matrix_rules', models.JSONField(default=exams.models.default_part2_matrix, verbose_name='Ma trận điểm Phần II (Số ý đúng -> Điểm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo đề')),
            ],
            options={
                'verbose_name': 'Đề thi',
                'verbose_name_plural': 'Danh sách Đề thi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('PART_I', 'Phần I: Trắc nghiệm 4 lựa chọn'), ('PART_II', 'Phần II: Đúng / Sai')], default='PART_I', max_length=20, verbose_name='Phần đề thi')),
                ('branch', models.CharField(choices=[('COMMON', 'Phần Chung (Bắt buộc)'), ('CS', 'Khoa học Máy tính (CS)'), ('ICT', 'Tin học Ứng dụng (ICT)')], default='COMMON', max_length=20, verbose_name='Phân nhánh chuyên đề')),
                ('order_index', models.IntegerField(default=1, verbose_name='Thứ tự gốc')),
                ('content', models.TextField(verbose_name='Nội dung câu hỏi (hỗ trợ LaTeX / Markdown)')),
                ('code_snippet', models.TextField(blank=True, verbose_name='Đoạn mã code (Code Snippet)')),
                ('code_language', models.CharField(default='python', max_length=30, verbose_name='Ngôn ngữ code (python / cpp / c / java)')),
                ('competency_category', models.CharField(choices=[('PROG_BASIC', 'Lập trình & Cú pháp cơ bản'), ('ALGO_DS', 'Thuật toán & Cấu trúc Dữ liệu'), ('OPTIMIZATION', 'Tối ưu hóa & Độ phức tạp'), ('DB_NETWORK', 'Cơ sở Dữ liệu & Mạng máy tính'), ('ICT_APP', 'Ứng dụng Tin học & Đa phương tiện')], default='PROG_BASIC', max_length=50, verbose_name='Ma trận Năng lực')),
                ('difficulty_level', models.CharField(choices=[('NB', 'Nhận biết'), ('TH', 'Thông hiểu'), ('VD', 'Vận dụng'), ('VDC', 'Vận dụng cao')], default='TH', max_length=20, verbose_name='Mức độ tư duy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='Đề thi')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Ngân hàng Câu hỏi',
                'ordering': ['part_type', 'branch', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, verbose_name='Ký hiệu (A/B/C/D hoặc a/b/c/d)')),
                ('content', models.TextField(verbose_name='Nội dung phương án')),
                ('code_snippet', models.TextField(blank=True, verbose_name='Mã code của phương án (nếu có)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Là đáp án đúng (hoặc Đúng trong Part II)')),
                ('order_index', models.IntegerField(default=1, verbose_name='Thứ tự')),
                ('explanation', models.TextField(blank=True, verbose_name='Lời giải chi tiết')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question', verbose_name='Câu hỏi')),
            ],
            options={
                'verbose_name': 'Phương án / Ý trả lời',
                'verbose_name_plural': 'Danh sách Phương án',
                'ordering': ['order_index'],
            },
        ),
    ]
