# Generated by Django 5.2.17 on 2026-08-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='matrix_preset',
            field=models.CharField(choices=[('HSG_QUAT_LAM', 'Chuẩn HSG THPT Quất Lâm (1=0.3, 2=0.6, 3=1.0, 4=1.5đ)'), ('BGD_2025', 'Chuẩn Đề thi Tốt nghiệp THPT 2025 Bộ GD&ĐT (1=0.1, 2=0.25, 3=0.5, 4=1.0đ)'), ('LINEAR_EQUAL', 'Tuyến tính Đều (1=0.25, 2=0.5, 3=0.75, 4=1.0đ)'), ('CUSTOM', 'Tùy chỉnh Ma trận Điểm')], default='HSG_QUAT_LAM', max_length=30, verbose_name='Preset Ma trận chấm Phần II'),
        ),
    ]
