# Generated by Django 5.2.17 on 2026-08-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_matrix_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assigned_classes',
            field=models.TextField(blank=True, default='Toàn trường', help_text='Danh sách lớp được giao đề (vd: 12A1, 12A2, Đội tuyển HSG, Toàn trường)', verbose_name='Lớp được giao'),
        ),
        migrations.AddField(
            model_name='exam',
            name='assigned_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hạn chót nộp bài'),
        ),
        migrations.AddField(
            model_name='exam',
            name='assigned_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu mở đề'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='Đã giao đề cho học sinh'),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_attempts',
            field=models.IntegerField(default=1, verbose_name='Số lần làm bài tối đa'),
        ),
    ]
