# Generated by Django 5.2.17 on 2026-08-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_assigned_classes_exam_assigned_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Lời giải / Hướng dẫn chi tiết'),
        ),
    ]
