# Generated by Django 5.2.17 on 2026-08-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='part1_total_points',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=6, verbose_name='Tổng điểm Phần I (Trắc nghiệm)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='part2_total_points',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=6, verbose_name='Tổng điểm Phần II (Đúng / Sai)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6, verbose_name='Tổng điểm bài thi'),
        ),
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='Điểm của câu hỏi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='part1_point_per_question',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4, verbose_name='Điểm mỗi câu Phần I (Mặc định)'),
        ),
    ]
