# Generated by Django 5.2.17 on 2026-08-27 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_part1_total_points_exam_part2_total_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='matrix_preset',
            field=models.CharField(choices=[('HSG_NINHBINH', 'Chuẩn Đề thi HSG Tỉnh Ninh Bình (30 câu P1 = 12đ, 7 câu P2 = 8đ, Thang 20đ)'), ('HSG_QUAT_LAM', 'Chuẩn HSG THPT Quất Lâm (30 câu P1 = 12đ, 7 câu P2 = 8đ, Thang 20đ)'), ('BGD_2025', 'Chuẩn Đề thi Tốt nghiệp THPT Bộ GD&ĐT (24 câu P1 = 6đ, 6 câu P2 = 4đ, Thang 10đ)'), ('LINEAR_EQUAL', 'Tuyến tính Đều (1=0.25, 2=0.5, 3=0.75, 4=1.0đ)'), ('CUSTOM', 'Tùy chỉnh Ma trận Điểm')], default='HSG_QUAT_LAM', max_length=30, verbose_name='Preset Ma trận chấm Phần II'),
        ),
        migrations.CreateModel(
            name='UserAISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI ChatGPT')], default='gemini', max_length=20, verbose_name='Nhà cung cấp AI')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key (Lưu trữ bảo mật)')),
                ('model', models.CharField(default='gemini-3.7-flash', max_length=100, verbose_name='Mô hình AI')),
                ('base_url', models.CharField(blank=True, max_length=255, verbose_name='Endpoint tùy chỉnh')),
                ('auto_explain', models.BooleanField(default=True, verbose_name='Tự động sinh lời giải chi tiết')),
                ('share_with_teachers', models.BooleanField(default=True, verbose_name='Cho phép chia sẻ API cho giáo viên được chọn')),
                ('use_shared_admin_api', models.BooleanField(default=False, verbose_name='Sử dụng API dùng chung do Super Admin chia sẻ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_teachers', models.ManyToManyField(blank=True, related_name='granted_admin_ai_settings', to=settings.AUTH_USER_MODEL, verbose_name='Danh sách Giáo viên được cấp quyền dùng API của Admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_setting', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Cấu hình AI Người dùng',
                'verbose_name_plural': 'Cấu hình AI Người dùng',
            },
        ),
    ]
