# Generated by Django 5.2.17 on 2026-08-27 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_exam_matrix_preset_useraisetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('HSG', 'Đề thi Học sinh giỏi (HSG THPT)'), ('TN_THPT', 'Đề ôn luyện thi Tốt nghiệp THPT')], default='HSG', max_length=20, verbose_name='Phân loại đề thi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_shared_with_all_teachers',
            field=models.BooleanField(default=False, verbose_name='Chia sẻ công khai cho tất cả giáo viên'),
        ),
        migrations.AddField(
            model_name='exam',
            name='shared_teachers',
            field=models.ManyToManyField(blank=True, related_name='shared_exams', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên được chia sẻ quyền sử dụng'),
        ),
    ]
