# Generated by Django 5.2.17 on 2026-09-03 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_exam_type_exam_is_shared_with_all_teachers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='show_explanation_after_test',
            field=models.BooleanField(default=True, verbose_name='Cho phép học sinh xem lời giải & đáp án chi tiết sau khi thi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_score_after_test',
            field=models.BooleanField(default=True, verbose_name='Cho phép học sinh xem điểm số sau khi thi'),
        ),
        migrations.CreateModel(
            name='QuestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(blank=True, null=True, verbose_name='Mã phiên thi (nếu có)')),
                ('feedback_type', models.CharField(choices=[('WRONG_KEY', 'Sai đáp án'), ('WRONG_CONTENT', 'Lỗi nội dung / câu hỏi'), ('TYPO', 'Lỗi hiển thị / chính tả'), ('OTHER', 'Khác')], default='WRONG_KEY', max_length=30, verbose_name='Phân loại phản ánh')),
                ('student_note', models.TextField(verbose_name='Mô tả / Phân tích chi tiết của học sinh')),
                ('suggested_option', models.CharField(blank=True, max_length=50, verbose_name='Đáp án đề xuất của học sinh')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('ACCEPTED', 'Đã chấp thuận & Sửa đáp án'), ('REJECTED', 'Từ chối phản ánh')], default='PENDING', max_length=20, verbose_name='Trạng thái xử lý')),
                ('teacher_reply', models.TextField(blank=True, verbose_name='Phản hồi của Giáo viên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='exams.exam', verbose_name='Đề thi')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='exams.question', verbose_name='Câu hỏi phản ánh')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên duyệt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Học sinh gửi phản ánh')),
            ],
            options={
                'verbose_name': 'Phản ánh câu hỏi',
                'verbose_name_plural': 'Danh sách Phản ánh câu hỏi',
                'ordering': ['-created_at'],
            },
        ),
    ]
