# Generated by Django 5.2.17 on 2026-09-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_show_explanation_after_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraisetting',
            name='api_key',
            field=models.TextField(blank=True, verbose_name='API Key (Mã hóa Fernet)'),
        ),
    ]
