# Generated by Django 5.2.17 on 2026-09-04 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_useraisetting_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('PART_I', 'Phần I: Trắc nghiệm 4 lựa chọn'), ('PART_II', 'Phần II: Đúng / Sai')], default='PART_I', max_length=20, verbose_name='Phần đề thi')),
                ('branch', models.CharField(choices=[('COMMON', 'Phần Chung (Bắt buộc)'), ('CS', 'Khoa học Máy tính (CS)'), ('ICT', 'Tin học Ứng dụng (ICT)')], default='COMMON', max_length=20, verbose_name='Phân nhánh chuyên đề')),
                ('content', models.TextField(verbose_name='Nội dung câu hỏi (hỗ trợ LaTeX / Markdown)')),
                ('code_snippet', models.TextField(blank=True, verbose_name='Đoạn mã code (Code Snippet)')),
                ('code_language', models.CharField(default='python', max_length=30, verbose_name='Ngôn ngữ code (python / cpp / c / java)')),
                ('competency_category', models.CharField(choices=[('PROG_BASIC', 'Lập trình & Cú pháp cơ bản'), ('ALGO_DS', 'Thuật toán & Cấu trúc Dữ liệu'), ('OPTIMIZATION', 'Tối ưu hóa & Độ phức tạp'), ('DB_NETWORK', 'Cơ sở Dữ liệu & Mạng máy tính'), ('ICT_APP', 'Ứng dụng Tin học & Đa phương tiện')], default='PROG_BASIC', max_length=50, verbose_name='Ma trận Năng lực')),
                ('difficulty_level', models.CharField(choices=[('NB', 'Nhận biết'), ('TH', 'Thông hiểu'), ('VD', 'Vận dụng'), ('VDC', 'Vận dụng cao')], default='TH', max_length=20, verbose_name='Mức độ tư duy')),
                ('explanation', models.TextField(blank=True, verbose_name='Lời giải / Hướng dẫn chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Câu hỏi Ngân hàng',
                'verbose_name_plural': 'Ngân hàng Câu hỏi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, verbose_name='Ký hiệu (A/B/C/D hoặc a/b/c/d)')),
                ('content', models.TextField(verbose_name='Nội dung phương án')),
                ('code_snippet', models.TextField(blank=True, verbose_name='Mã code của phương án (nếu có)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Là đáp án đúng (hoặc Đúng trong Part II)')),
                ('order_index', models.IntegerField(default=1, verbose_name='Thứ tự')),
                ('explanation', models.TextField(blank=True, verbose_name='Lời giải chi tiết')),
                ('bank_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.bankquestion', verbose_name='Câu hỏi gốc')),
            ],
            options={
                'verbose_name': 'Phương án Ngân hàng',
                'verbose_name_plural': 'Danh sách Phương án Ngân hàng',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên chuyên đề / Thư mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='exams.questioncategory', verbose_name='Thư mục cha')),
            ],
            options={
                'verbose_name': 'Thư mục câu hỏi',
                'verbose_name_plural': 'Quản lý Thư mục câu hỏi',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.questioncategory', verbose_name='Thư mục'),
        ),
    ]
