# Generated by Django 5.2.17 on 2026-09-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_bankquestion_bankquestionoption_questioncategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='branch_mode',
            field=models.CharField(choices=[('SINGLE', 'Học sinh chỉ được phép làm CS hoặc ICT (Chọn 1 trong 2)'), ('BOTH', 'Học sinh được phép làm cả CS và ICT (Thời gian giữ nguyên)')], default='SINGLE', max_length=20, verbose_name='Chế độ phân nhánh chuyên đề Phần II'),
        ),
    ]
