# Generated by Django 5.2.17 on 2026-09-13 15:05

import django.db.models.deletion
import exams.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_exam_branch_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên ca thi')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('room_code', models.CharField(default=exams.models.generate_room_code, max_length=20, unique=True, verbose_name='Mã phòng thi')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Mật khẩu vào thi')),
                ('assigned_classes', models.TextField(blank=True, default='Toàn trường', verbose_name='Lớp / Đối tượng')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Giờ mở thi')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hạn chót nộp bài')),
                ('max_attempts', models.IntegerField(default=1, verbose_name='Số lần làm bài tối đa')),
                ('distribution_mode', models.CharField(choices=[('RANDOM', 'Ngẫu nhiên (cân bằng số lượng)'), ('ROUND_ROBIN', 'Tuần tự (xoay vòng theo thứ tự)'), ('MANUAL', 'Thủ công (Học sinh tự chọn đề)')], default='RANDOM', max_length=20, verbose_name='Chế độ phân đề')),
                ('is_active', models.BooleanField(default=False, verbose_name='Đang hoạt động')),
                ('show_score_after_test', models.BooleanField(default=True, verbose_name='Cho xem điểm sau thi')),
                ('show_explanation_after_test', models.BooleanField(default=True, verbose_name='Cho xem đáp án sau thi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sittings', to=settings.AUTH_USER_MODEL)),
                ('exams', models.ManyToManyField(blank=True, related_name='sittings', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Ca thi',
                'verbose_name_plural': 'Danh sách Ca thi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SittingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitting_assignments', to='exams.exam')),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.examsitting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitting_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phân đề Ca thi',
                'verbose_name_plural': 'Phân đề Ca thi',
                'unique_together': {('sitting', 'student')},
            },
        ),
    ]
