# Generated by Django 5.2.17 on 2026-09-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_examsitting_sittingassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allow_run_code',
            field=models.BooleanField(default=True, verbose_name='Cho phép học sinh chạy thử Code (IDE)'),
        ),
        migrations.AddField(
            model_name='examsitting',
            name='allow_run_code',
            field=models.BooleanField(default=True, verbose_name='Cho phép học sinh chạy thử Code (IDE)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_tab_violations',
            field=models.IntegerField(default=5, verbose_name='Số lần tối đa chuyển tab/cửa sổ'),
        ),
    ]
