# Generated by Django 5.2.17 on 2026-09-15 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_exam_allow_run_code_examsitting_allow_run_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên thư mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Thư mục dùng chung toàn trường / tổ bộ môn')),
                ('color', models.CharField(default='blue', max_length=30, verbose_name='Màu sắc hiển thị')),
                ('icon', models.CharField(default='folder', max_length=50, verbose_name='Biểu tượng icon')),
                ('order_index', models.IntegerField(default=1, verbose_name='Thứ tự sắp xếp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_folders', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exams.examfolder', verbose_name='Thư mục cha')),
            ],
            options={
                'verbose_name': 'Thư mục đề thi',
                'verbose_name_plural': 'Quản lý Thư mục đề thi',
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.examfolder', verbose_name='Thư mục đề thi'),
        ),
    ]
