# Generated by Django 5.2.17 on 2026-09-16 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_examfolder_exam_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_active', 'is_assigned'], name='exams_exam_is_acti_ac5c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['folder', 'is_active'], name='exams_exam_folder__a583ce_idx'),
        ),
        migrations.AddIndex(
            model_name='examfolder',
            index=models.Index(fields=['parent', 'order_index'], name='exams_examf_parent__6c7fda_idx'),
        ),
        migrations.AddIndex(
            model_name='examfolder',
            index=models.Index(fields=['creator', 'is_shared'], name='exams_examf_creator_34a8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'part_type', 'order_index'], name='exams_quest_exam_id_787124_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'branch'], name='exams_quest_exam_id_1ba17d_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'order_index'], name='exams_quest_questio_119d9c_idx'),
        ),
    ]
