# Generated by Django 5.2.17 on 2026-09-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_exam_exams_exam_is_acti_ac5c7b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='matrix_preset',
            field=models.CharField(choices=[('HSG_NINHBINH', 'Chuẩn Đề thi HSG (30 câu P1 = 12đ, 7 câu P2 = 8đ, Thang 20đ)'), ('HSG_QUAT_LAM', 'Chuẩn HSG THPT Quất Lâm (30 câu P1 = 12đ, 7 câu P2 = 8đ, Thang 20đ)'), ('BGD_2025', 'Chuẩn Đề thi Tốt nghiệp THPT Bộ GD&ĐT (24 câu P1 = 6đ, 6 câu P2 = 4đ, Thang 10đ)'), ('LINEAR_EQUAL', 'Tuyến tính Đều (1=0.25, 2=0.5, 3=0.75, 4=1.0đ)'), ('CUSTOM', 'Tùy chỉnh Ma trận Điểm')], default='HSG_QUAT_LAM', max_length=30, verbose_name='Preset Ma trận chấm Phần II'),
        ),
    ]
